--- # My Conditional playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks: 
    - name: Install httpd for Debian family
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"
    - name: Install httpd for redhat
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"
